apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api-deployment
  labels:
    app: heart-disease-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
      - name: heart-disease-api
        image: heart-disease-api:latest
        imagePullPolicy: Never # Forces K8s to use your local Docker image
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://20.17.177.233:5000"

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
