apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  type: LoadBalancer # Exposes the service externally
  selector:
    app: grafana     # Must match the labels in your Grafana Deployment
  ports:
    - protocol: TCP
      port: 3000     # The port you will hit in your browser
      targetPort: 3000 # The port the Grafana container is listening on
