name: MLOps CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Data Acquisition
      run: python src/download_data.py
      
    - name: Run Data Preparation
      run: python src/data_prep.py
      
    - name: Train Model & Track Experiments
      run: python src/train.py

    - name: Lint code with flake8
      run: |
        flake8 src/ tests/ api/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ tests/ api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
    - name: Run Unit Tests
      run: pytest tests/
      
    - name: Upload Plot Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-plots
        path: plots/

    - name: Trigger Jenkins CD Pipeline
      if: success() && github.ref == 'refs/heads/main'
      run: |
        curl -X POST "http://${{ secrets.JENKINS_IP }}:8080/job/MLOps-Deployment/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}" \
        --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
